// =============================================================================
// CyberRiskOS — AI Explanation Assistant Types
// Phase: Phase 8 — AI Explanation Assistant
// Owner: TANISH (Risk Intelligence, Quantification & Decision Engine Lead)
// Spec: docs/API_CONTRACTS.md (Section 8) & docs/GROUNDING_SPECIFICATION.md
// =============================================================================

export type ExplanationRequestType = 'EXPLAIN_RISK' | 'EXPLAIN_FINANCIAL' | 'COMPARE_STRATEGIES';

/**
 * Lifecycle status of an AI explanation response.
 *
 * TEMPLATE_GENERATED : Deterministic template engine used; no external AI provider configured.
 * AI_GENERATED        : Successfully generated by external AI provider AND passed grounding.
 * GROUNDING_FAILED    : AI response was generated but did NOT pass ground truth anchor validation.
 *                       The deterministic template explanation is returned as a safe fallback.
 * PROVIDER_ERROR      : External AI provider returned an error or timed out.
 *                       The deterministic template explanation is returned as a safe fallback.
 * AI_UNAVAILABLE      : AI provider is not configured (env var missing/not set).
 */
export type ExplanationStatus =
  | 'TEMPLATE_GENERATED'
  | 'AI_GENERATED'
  | 'GROUNDING_FAILED'
  | 'PROVIDER_ERROR'
  | 'AI_UNAVAILABLE';

// ---------------------------------------------------------------------------
// Shared Sub-types
// ---------------------------------------------------------------------------

export interface FactorContributionDTO {
  factorName: string;
  contribution: number;
  description: string;
}

// ---------------------------------------------------------------------------
// Authoritative Resolution Request DTOs
// ---------------------------------------------------------------------------

/**
 * Authoritative Risk Explanation Request:
 * Primary mode: Pass `riskResultId` to resolve exact persisted record from database.
 * Fallback mode: Pass `assetId` + `cveId` to query/evaluate server-side.
 * Frontend MUST NOT provide risk score as ground truth.
 */
export interface RiskExplanationRequestDTO {
  riskResultId?: string;
  assetId?: string;
  cveId?: string;
  // Deprecated/Ignored if provided by client; backend resolves ground truth.
  assetName?: string;
  modelVersion?: string;
}

/**
 * Authoritative Financial Explanation Request:
 * Primary mode: Pass `financialResultId` to resolve exact persisted record.
 * Fallback mode: Pass `assetId` + `cveId` to query server-side.
 * Frontend MUST NOT provide SLE, ALEF, or EAL as ground truth.
 */
export interface FinancialExplanationRequestDTO {
  financialResultId?: string;
  assetId?: string;
  cveId?: string;
  currency?: string;
}

export interface StrategyItemDTO {
  strategyId: string;
  strategyName: string;
  totalCost: number;
  totalRiskReduction: number;
  totalEalReduction: number | null;     // Nullable / status-aware when EAL inputs unavailable
  ealStatus?: 'CALCULATED' | 'NOT_AVAILABLE';
  rosiPct: number | null;
  actionCount: number;
  description: string;
}

/**
 * Authoritative Strategy Comparison Request:
 * Primary mode: Pass `optimizationResultId` + `strategyIds` to resolve from cache/solver.
 * Fallback mode: Pass `budgetLimit` + `candidateActions` to execute server-side optimizer.
 * Frontend MUST NOT provide strategy costs or ROSI figures as ground truth.
 */
export interface StrategyComparisonRequestDTO {
  optimizationResultId?: string;
  strategyIds?: string[];
  budgetLimit?: number;
  currency?: string;
  candidateActions?: any[];
}

// ---------------------------------------------------------------------------
// Internal Resolved Ground Truth Contracts
// ---------------------------------------------------------------------------

export interface ResolvedRiskContext {
  riskResultId: string;
  assetId: string;
  assetName: string;
  cveId: string;
  riskScore: number;
  severity: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
  factors: FactorContributionDTO[];
  dataCompleteness: number;
  missingDataWarnings: string[];
  modelVersion: string;
  evaluatedAt: string;
}

export interface ResolvedFinancialContext {
  financialResultId: string;
  assetId: string;
  assetName: string;
  cveId: string;
  sle: number | null;
  alef: number | null;
  eal: number | null;
  ealStatus: 'CALCULATED' | 'NOT_AVAILABLE';
  currency: string;
  primaryLoss: number | null;
  secondaryLoss: number | null;
  estimatedOutageHours: number | null;
  dataCompleteness: number;
  modelVersion: string;
}

export interface ResolvedStrategyComparisonContext {
  optimizationResultId: string;
  strategyA: StrategyItemDTO;
  strategyB: StrategyItemDTO;
  budgetLimit: number;
  currency: string | null;
}

// ---------------------------------------------------------------------------
// Grounding & Structured Claim Validation
// ---------------------------------------------------------------------------

export interface GroundingAnchor {
  field: string;
  expectedValue: number;
  tolerancePct?: number;
}

export interface StructuredClaimDTO {
  sourceField: string;
  claimedValue: number | string | null;
  isVerified: boolean;
  expectedValue?: number | string | null;
  note?: string;
}

export interface GroundingViolationDTO {
  field: string;
  expectedValue: number;
  tolerancePct: number;
  note: string;
}

export interface GroundingValidationDTO {
  passed: boolean;
  anchorCount: number;
  verifiedCount: number;
  violations: GroundingViolationDTO[];
  structuredClaims?: StructuredClaimDTO[];
  validationNote: string;
}

// ---------------------------------------------------------------------------
// Response DTO
// ---------------------------------------------------------------------------

export interface AIExplanationResponseDTO {
  requestType: ExplanationRequestType;
  explanationStatus: ExplanationStatus;
  explanation: string;
  groundingValidation: GroundingValidationDTO;
  promptGroundingCitation: string;
  aiProvider: string;
  modelVersion: string;
  generatedAt: string;
  warnings: string[];
  integrationStatus?: string;
}
